### ISSUE TITLE
A better domain

### ISSUE THREAD

**Issue by chriszs** [BadIdeaFactory/bad-decision-maker#16]

**Comment by slifty** [comment]
BIF can pay for this (if you wanted to own it yourself you can get it back later! as project owner)

Just say what domain you want and we'll buy it via our gandi account

**Comment by chriszs** [comment]
Would a subdomain make sense here?

**Comment by slifty** [comment]
Yeah that's legit too; what do you have in mind?  Just let me know (here or in slack) what I should point DNS to.

**Comment by chriszs** [comment]
CNAME decisions.biffud.com jovial-northcutt-ffc0c1.netlify.com ought to do for now.

**Comment by chriszs** [comment]
Once that record is in place I can add it to Netlify and Let’s Encrypt will work

**Comment by chriszs** [comment]
Gentle reminder.

**Comment by chriszs** [comment]
https://baddecisions.app/
